server:
  port: ${SERVER_PORT:8080}
  max-http-request-header-size: 1MB
  shutdown: graceful
  servlet:
    context-path: /
spring:
  application:
    name: jetbrains-cloud
  threads:
    virtual:
      enabled: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  lifecycle:
    timeout-per-shutdown-phase: 60s
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 1000
    use-code-as-default-message: false
    always-use-message-format: false
    fallback-to-system-locale: true
  datasource:
    hikari:
      pool-name: hp
      minimum-idle: 4
      maximum-pool-size: 8
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      username: ${REDIS_USER}
      password: ${REDIS_PASS}
      connect-timeout: ${REDIS_TIMEOUT:3s}
      timeout: ${REDIS_TIMEOUT:3s}
      lettuce:
        pool:
          enabled: true
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    shutdown:
      enabled: off
logging:
  config: classpath:logging/logback-spring.xml
  file:
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 1GB
      total-size-cap: 10GB
      max-history: 15
  level:
    com.makto.seetaface: debug
mybatis-plus:
  type-aliases-package: com.framework.cloud.**.entity
  mapper-locations: classpath*:com/framework/cloud/**/domain/mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  setting:
    swagger-model-name: Model
    enable-footer-custom: true
    footer-custom-content: '@2024 all rights reserved.'
    enable-host-text: 127.0.0.1:8080
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
  group-configs:
    - group: 'f'
      display-name: 'Face Services'
      paths-to-match: '/api/**'
      packages-to-scan: 'com.framework.cloud.controller'